import torch
import torch.nn as nn

class ImaginationEnv(nn.Module):
    """
    Simulates the world model into the future using the actor policy.
    Used for DreamerV3 style Actor-Critic training in latent space.
    """
    def __init__(self, rssm, actor, horizon: int = 15):
        super().__init__()
        self.rssm = rssm
        self.actor = actor
        self.horizon = horizon

    def rollout(self, start_state):
        """
        Unrolls the RSSM for H steps using actions generated by the actor policy.
        
        Args:
            start_state: Dict with 'deter' and 'stoch' representing the beginning state.
                         Shape is usually [B, D].
        Returns:
            states: List of state dictionaries of length H.
            actions: Tensor of shape [H, B, ActionDim].
        """
        states = []
        actions = []
        curr_state = start_state
        
        for _ in range(self.horizon):
            # 1. Actor picks action based on current state
            # Actor is expected to take deterministic and stochastic features
            action = self.actor(curr_state['deter'], curr_state['stoch'].view(curr_state['stoch'].size(0), -1))
            
            # 2. Step the world model (imagination, no embed = prior dynamics)
            # rssm.step returns: prior, posterior, current_state
            _, _, curr_state = self.rssm.step(curr_state, action, embed=None)
            
            states.append(curr_state)
            actions.append(action)
            
        return states, torch.stack(actions, dim=0)
