import torch
import torch.nn as nn
import copy

class JEPATrunk(nn.Module):
    """
    Context Encoder (Shared Trunk) for the Joint-Embedding Predictive Architecture.
    Processes unmasked patches/tokens and maps them to high-level semantic representations.
    """
    def __init__(self, embed_dim=256, num_heads=8, num_layers=6):
        super().__init__()
        self.embed_dim = embed_dim
        
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=embed_dim, 
            nhead=num_heads, 
            dim_feedforward=embed_dim * 4,
            batch_first=True,
            activation='gelu'
        )
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
        self.layer_norm = nn.LayerNorm(embed_dim)

    def forward(self, x: torch.Tensor, mask_indices=None):
        """
        x: [Batch, SeqLen, EmbedDim]
        mask_indices: Optional boolean mask specifying which tokens to process.
        """
        # In a full I-JEPA, x would be pruned to only contain context (unmasked) elements
        encoded = self.transformer(x)
        return self.layer_norm(encoded)

class JEPAPredictor(nn.Module):
    """
    Given the contextual representation from the JEPATrunk, the predictor tries to 
    predict the representations (generated by the EMA target encoder) for the masked regions.
    """
    def __init__(self, embed_dim=256, num_heads=8, num_layers=3):
        super().__init__()
        
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=embed_dim, 
            nhead=num_heads, 
            dim_feedforward=embed_dim * 4,
            batch_first=True,
            activation='gelu'
        )
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
        self.layer_norm = nn.LayerNorm(embed_dim)

    def forward(self, context_representations: torch.Tensor):
        """
        In standard JEPA, target mask tokens (with target positional encodings) 
        are concatenated to context_representations before passing to this transformer.
        Here we simplify to a direct mapping for generalization.
        """
        pred = self.transformer(context_representations)
        return self.layer_norm(pred)

def update_ema_target(encoder: JEPATrunk, target_encoder: JEPATrunk, momentum=0.996):
    """
    Updates the target encoder parameters towards the context encoder using EMA.
    """
    with torch.no_grad():
        for param_q, param_k in zip(encoder.parameters(), target_encoder.parameters()):
            param_k.data.mul_(momentum).add_((1 - momentum) * param_q.detach().data)
